export const TauriCommands = {
	MUSIC_PLAY: 'music_play',
	MUSIC_PAUSE: 'music_pause',
	MUSIC_NEXT: 'music_next',
	MUSIC_PREVIOUS: 'music_previous',
	MUSIC_CLEAR: 'music_clear',
	MUSIC_REPEAT_MODE_SET: 'music_repeat_mode_set',
	MUSIC_PLAYER_SYNC: 'music_player_sync',
	MUSIC_PLAYER_REQUEST_SYNC: 'music_player_request_sync',
	LIBRARY_SYNC: 'library_sync',
	MUSIC_INFO_GET: 'music_info_get',
	MUSIC_POSITION_SET: 'music_position_set',
	MUSIC_QUEUE_ADD: 'music_queue_add',
	MUSIC_DIRECTORY_REQUEST: 'music_directory_request',
	MUSIC_HEADSET_CHANGE: 'music_headset_change',
	MUSIC_QUEUE_REMOVE: 'music_queue_remove',
	MUSIC_QUEUE_GOTO: 'music_queue_goto',
	MUSIC_QUEUE_MOVETO: 'music_queue_moveto',
	MUSIC_QUEUE_SHUFFLE: 'music_queue_shuffle',
	MUSIC_QUEUE_COUNT_GET: 'music_queue_count_get',
	MUSIC_QUEUE_GET_BY_INDEX: 'music_queue_get_by_index',
	MUSIC_VOLUME_SET: 'music_volume_set',
	MUSIC_EQUALIZER: 'music_equalizer',
	MUSIC_EQUALIZER_RESET: 'music_equalizer_reset',
	MUSIC_IMAGE_GET: 'music_image_get',
	MUSIC_DEFAULT_COVER_ART_GET: 'music_default_cover_art_get',
	MUSIC_VISUALIZER_BUFFER_GET: 'music_visualizer_buffer_get',
	MUSIC_CURRENT_DURATION_GET: 'music_current_duration_get',
	MUSIC_LYRICS_GET: 'music_lyrics_get',
	MUSIC_BIT_PERFECT_TOGGLE: 'music_bit_perfect_toggle',

	// Library (Rust-side state)
	LIBRARY_LOAD: 'library_load',
	LIBRARY_MUSIC_COUNT_GET: 'library_music_count_get',
	LIBRARY_MUSIC_GET_BY_INDEX: 'library_music_get_by_index',
	LIBRARY_MUSIC_GET_BY_PATH: 'library_music_get_by_path',
	LIBRARY_ALBUM_COUNT_GET: 'library_album_count_get',
	LIBRARY_ALBUM_GET_BY_INDEX: 'library_album_get_by_index',
	LIBRARY_ALBUM_GET_FIRST_BY_INDEX: 'library_album_get_first_by_index',
	LIBRARY_COLLECTION_ADD_AND_PLAY: 'library_collection_add_and_play',
	LIBRARY_COLLECTION_ADD_TO_QUEUE: 'library_collection_add_to_queue',
	LIBRARY_COLLECTION_SHUFFLE_AND_PLAY: 'library_collection_shuffle_and_play',
	LIBRARY_FOLDER_INFO_GET: 'library_folder_info_get',
	LIBRARY_FOLDERS_FILTER_HAS_MUSIC: 'library_folders_filter_has_music',

	PLAYLIST_ALL_GET: 'playlist_all_get',
	PLAYLIST_CREATE: 'playlist_create',
	PLAYLIST_DELETE: 'playlist_delete',
	PLAYLIST_IMAGE_UPLOAD: 'playlist_image_upload',
	PLAYLIST_IMAGE_READ: 'playlist_image_read',

	FOLDER_ITEMS_GET: 'folder_items_get',
	FOLDER_FIRST_MUSIC_PATH_GET: 'folder_first_music_path_get',

	SIDEBAR_MOUSE_LEAVE: 'sidebar_mouse_leave',

	AUDIO_PERMISSION_READ_CHECK: 'audio_permission_read_check',
	AUDIO_PERMISSION_READ_REQUEST: 'audio_permission_read_request',

	NAVIGATION_BAR_HEIGHT_GET: 'navigation_bar_height_get',
	STATUS_BAR_HEIGHT_GET: 'status_bar_height_get',
	NAVIGATION_BAR_VISIBILITY_SET: 'navigation_bar_visibility_set',
	ANDROID_DIRECTORY_REQUEST: 'android_directory_request',

	LOG: 'log',

	COVER_ART_GET: 'cover_art_get',
	LYRIC_GET: 'lyric_get',
	ANIMATED_BACKGROUND_UPDATE: 'animated_background_update',
	ANIMATED_BACKGROUND_RESTORE: 'animated_background_restore',

	DEVELOPER_LOG_SAVE: 'developer_log_save',
	DEVELOPER_MPV_LOG_SAVE: 'developer_mpv_log_save',

	UPDATE_CHECK: 'update_check'
};
