// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(fluyer_coreFFI)
import fluyer_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_fluyer_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_fluyer_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    public static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




public protocol FluyerAppEngineProtocol : AnyObject {
    
    func cycleRepeat() 
    
    func generateBackgroundForCurrent(width: UInt32, height: UInt32)  -> Data?
    
    func getActiveLyricIndex(positionMs: UInt64)  -> Int32
    
    func getAlbumCard(index: UInt64)  -> AlbumCardViewModel?
    
    func getAlbumCount()  -> UInt64
    
    func getAlbumDetail(index: UInt64)  -> AlbumDetailViewModel?
    
    func getAlbumImage(index: UInt64)  -> Data?
    
    func getAlbumThumbnailRgba(index: UInt64, width: UInt32, height: UInt32)  -> Data?
    
    func getAlbumTracks(albumIndex: UInt64)  -> [TrackItemViewModel]
    
    func getAlbumView(index: UInt64)  -> AlbumCardViewModel?
    
    func getCurrentImage()  -> Data?
    
    func getLyrics()  -> [LyricLine]
    
    func getPlayView()  -> PlayViewModel
    
    func getPlayerBarView()  -> PlayerBarViewModel
    
    func getScanStatus()  -> ScanStatusViewModel
    
    func getTrackCount()  -> UInt64
    
    func getTrackImage(index: UInt64)  -> Data?
    
    func getTrackThumbnailRgba(index: UInt64, width: UInt32, height: UInt32)  -> Data?
    
    func getTrackView(index: UInt64)  -> TrackItemViewModel?
    
    func next() 
    
    func pause() 
    
    func play() 
    
    func playAlbum(index: UInt64) 
    
    func playAlbumTrack(albumIndex: UInt64, trackIndex: UInt64) 
    
    func playAllFromLibrary(startIndex: UInt64) 
    
    func playSingleFromLibrary(index: UInt64) 
    
    func previous() 
    
    func queueAlbum(index: UInt64) 
    
    func requestSync() 
    
    func scanDirectories(directories: [String]) 
    
    func seek(positionMs: UInt64) 
    
    func setRepeatMode(mode: NativeRepeatMode) 
    
    func setVolume(volume: Float) 
    
    func shuffle() 
    
    func shuffleAlbum(index: UInt64) 
    
    func togglePlay() 
    
}

open class FluyerAppEngine:
    FluyerAppEngineProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_fluyer_core_fn_clone_fluyerappengine(self.pointer, $0) }
    }
public convenience init(dataDir: String, cacheDir: String, listener: FluyerEventListener?)throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeFluyerError.lift) {
    uniffi_fluyer_core_fn_constructor_fluyerappengine_new(
        FfiConverterString.lower(dataDir),
        FfiConverterString.lower(cacheDir),
        FfiConverterOptionCallbackInterfaceFluyerEventListener.lower(listener),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_fluyer_core_fn_free_fluyerappengine(pointer, $0) }
    }

    

    
open func cycleRepeat() {try! rustCall() {
    uniffi_fluyer_core_fn_method_fluyerappengine_cycle_repeat(self.uniffiClonePointer(),$0
    )
}
}
    
open func generateBackgroundForCurrent(width: UInt32, height: UInt32) -> Data? {
    return try!  FfiConverterOptionData.lift(try! rustCall() {
    uniffi_fluyer_core_fn_method_fluyerappengine_generate_background_for_current(self.uniffiClonePointer(),
        FfiConverterUInt32.lower(width),
        FfiConverterUInt32.lower(height),$0
    )
})
}
    
open func getActiveLyricIndex(positionMs: UInt64) -> Int32 {
    return try!  FfiConverterInt32.lift(try! rustCall() {
    uniffi_fluyer_core_fn_method_fluyerappengine_get_active_lyric_index(self.uniffiClonePointer(),
        FfiConverterUInt64.lower(positionMs),$0
    )
})
}
    
open func getAlbumCard(index: UInt64) -> AlbumCardViewModel? {
    return try!  FfiConverterOptionTypeAlbumCardViewModel.lift(try! rustCall() {
    uniffi_fluyer_core_fn_method_fluyerappengine_get_album_card(self.uniffiClonePointer(),
        FfiConverterUInt64.lower(index),$0
    )
})
}
    
open func getAlbumCount() -> UInt64 {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_fluyer_core_fn_method_fluyerappengine_get_album_count(self.uniffiClonePointer(),$0
    )
})
}
    
open func getAlbumDetail(index: UInt64) -> AlbumDetailViewModel? {
    return try!  FfiConverterOptionTypeAlbumDetailViewModel.lift(try! rustCall() {
    uniffi_fluyer_core_fn_method_fluyerappengine_get_album_detail(self.uniffiClonePointer(),
        FfiConverterUInt64.lower(index),$0
    )
})
}
    
open func getAlbumImage(index: UInt64) -> Data? {
    return try!  FfiConverterOptionData.lift(try! rustCall() {
    uniffi_fluyer_core_fn_method_fluyerappengine_get_album_image(self.uniffiClonePointer(),
        FfiConverterUInt64.lower(index),$0
    )
})
}
    
open func getAlbumThumbnailRgba(index: UInt64, width: UInt32, height: UInt32) -> Data? {
    return try!  FfiConverterOptionData.lift(try! rustCall() {
    uniffi_fluyer_core_fn_method_fluyerappengine_get_album_thumbnail_rgba(self.uniffiClonePointer(),
        FfiConverterUInt64.lower(index),
        FfiConverterUInt32.lower(width),
        FfiConverterUInt32.lower(height),$0
    )
})
}
    
open func getAlbumTracks(albumIndex: UInt64) -> [TrackItemViewModel] {
    return try!  FfiConverterSequenceTypeTrackItemViewModel.lift(try! rustCall() {
    uniffi_fluyer_core_fn_method_fluyerappengine_get_album_tracks(self.uniffiClonePointer(),
        FfiConverterUInt64.lower(albumIndex),$0
    )
})
}
    
open func getAlbumView(index: UInt64) -> AlbumCardViewModel? {
    return try!  FfiConverterOptionTypeAlbumCardViewModel.lift(try! rustCall() {
    uniffi_fluyer_core_fn_method_fluyerappengine_get_album_view(self.uniffiClonePointer(),
        FfiConverterUInt64.lower(index),$0
    )
})
}
    
open func getCurrentImage() -> Data? {
    return try!  FfiConverterOptionData.lift(try! rustCall() {
    uniffi_fluyer_core_fn_method_fluyerappengine_get_current_image(self.uniffiClonePointer(),$0
    )
})
}
    
open func getLyrics() -> [LyricLine] {
    return try!  FfiConverterSequenceTypeLyricLine.lift(try! rustCall() {
    uniffi_fluyer_core_fn_method_fluyerappengine_get_lyrics(self.uniffiClonePointer(),$0
    )
})
}
    
open func getPlayView() -> PlayViewModel {
    return try!  FfiConverterTypePlayViewModel.lift(try! rustCall() {
    uniffi_fluyer_core_fn_method_fluyerappengine_get_play_view(self.uniffiClonePointer(),$0
    )
})
}
    
open func getPlayerBarView() -> PlayerBarViewModel {
    return try!  FfiConverterTypePlayerBarViewModel.lift(try! rustCall() {
    uniffi_fluyer_core_fn_method_fluyerappengine_get_player_bar_view(self.uniffiClonePointer(),$0
    )
})
}
    
open func getScanStatus() -> ScanStatusViewModel {
    return try!  FfiConverterTypeScanStatusViewModel.lift(try! rustCall() {
    uniffi_fluyer_core_fn_method_fluyerappengine_get_scan_status(self.uniffiClonePointer(),$0
    )
})
}
    
open func getTrackCount() -> UInt64 {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_fluyer_core_fn_method_fluyerappengine_get_track_count(self.uniffiClonePointer(),$0
    )
})
}
    
open func getTrackImage(index: UInt64) -> Data? {
    return try!  FfiConverterOptionData.lift(try! rustCall() {
    uniffi_fluyer_core_fn_method_fluyerappengine_get_track_image(self.uniffiClonePointer(),
        FfiConverterUInt64.lower(index),$0
    )
})
}
    
open func getTrackThumbnailRgba(index: UInt64, width: UInt32, height: UInt32) -> Data? {
    return try!  FfiConverterOptionData.lift(try! rustCall() {
    uniffi_fluyer_core_fn_method_fluyerappengine_get_track_thumbnail_rgba(self.uniffiClonePointer(),
        FfiConverterUInt64.lower(index),
        FfiConverterUInt32.lower(width),
        FfiConverterUInt32.lower(height),$0
    )
})
}
    
open func getTrackView(index: UInt64) -> TrackItemViewModel? {
    return try!  FfiConverterOptionTypeTrackItemViewModel.lift(try! rustCall() {
    uniffi_fluyer_core_fn_method_fluyerappengine_get_track_view(self.uniffiClonePointer(),
        FfiConverterUInt64.lower(index),$0
    )
})
}
    
open func next() {try! rustCall() {
    uniffi_fluyer_core_fn_method_fluyerappengine_next(self.uniffiClonePointer(),$0
    )
}
}
    
open func pause() {try! rustCall() {
    uniffi_fluyer_core_fn_method_fluyerappengine_pause(self.uniffiClonePointer(),$0
    )
}
}
    
open func play() {try! rustCall() {
    uniffi_fluyer_core_fn_method_fluyerappengine_play(self.uniffiClonePointer(),$0
    )
}
}
    
open func playAlbum(index: UInt64) {try! rustCall() {
    uniffi_fluyer_core_fn_method_fluyerappengine_play_album(self.uniffiClonePointer(),
        FfiConverterUInt64.lower(index),$0
    )
}
}
    
open func playAlbumTrack(albumIndex: UInt64, trackIndex: UInt64) {try! rustCall() {
    uniffi_fluyer_core_fn_method_fluyerappengine_play_album_track(self.uniffiClonePointer(),
        FfiConverterUInt64.lower(albumIndex),
        FfiConverterUInt64.lower(trackIndex),$0
    )
}
}
    
open func playAllFromLibrary(startIndex: UInt64) {try! rustCall() {
    uniffi_fluyer_core_fn_method_fluyerappengine_play_all_from_library(self.uniffiClonePointer(),
        FfiConverterUInt64.lower(startIndex),$0
    )
}
}
    
open func playSingleFromLibrary(index: UInt64) {try! rustCall() {
    uniffi_fluyer_core_fn_method_fluyerappengine_play_single_from_library(self.uniffiClonePointer(),
        FfiConverterUInt64.lower(index),$0
    )
}
}
    
open func previous() {try! rustCall() {
    uniffi_fluyer_core_fn_method_fluyerappengine_previous(self.uniffiClonePointer(),$0
    )
}
}
    
open func queueAlbum(index: UInt64) {try! rustCall() {
    uniffi_fluyer_core_fn_method_fluyerappengine_queue_album(self.uniffiClonePointer(),
        FfiConverterUInt64.lower(index),$0
    )
}
}
    
open func requestSync() {try! rustCall() {
    uniffi_fluyer_core_fn_method_fluyerappengine_request_sync(self.uniffiClonePointer(),$0
    )
}
}
    
open func scanDirectories(directories: [String]) {try! rustCall() {
    uniffi_fluyer_core_fn_method_fluyerappengine_scan_directories(self.uniffiClonePointer(),
        FfiConverterSequenceString.lower(directories),$0
    )
}
}
    
open func seek(positionMs: UInt64) {try! rustCall() {
    uniffi_fluyer_core_fn_method_fluyerappengine_seek(self.uniffiClonePointer(),
        FfiConverterUInt64.lower(positionMs),$0
    )
}
}
    
open func setRepeatMode(mode: NativeRepeatMode) {try! rustCall() {
    uniffi_fluyer_core_fn_method_fluyerappengine_set_repeat_mode(self.uniffiClonePointer(),
        FfiConverterTypeNativeRepeatMode.lower(mode),$0
    )
}
}
    
open func setVolume(volume: Float) {try! rustCall() {
    uniffi_fluyer_core_fn_method_fluyerappengine_set_volume(self.uniffiClonePointer(),
        FfiConverterFloat.lower(volume),$0
    )
}
}
    
open func shuffle() {try! rustCall() {
    uniffi_fluyer_core_fn_method_fluyerappengine_shuffle(self.uniffiClonePointer(),$0
    )
}
}
    
open func shuffleAlbum(index: UInt64) {try! rustCall() {
    uniffi_fluyer_core_fn_method_fluyerappengine_shuffle_album(self.uniffiClonePointer(),
        FfiConverterUInt64.lower(index),$0
    )
}
}
    
open func togglePlay() {try! rustCall() {
    uniffi_fluyer_core_fn_method_fluyerappengine_toggle_play(self.uniffiClonePointer(),$0
    )
}
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFluyerAppEngine: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = FluyerAppEngine

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> FluyerAppEngine {
        return FluyerAppEngine(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: FluyerAppEngine) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FluyerAppEngine {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: FluyerAppEngine, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFluyerAppEngine_lift(_ pointer: UnsafeMutableRawPointer) throws -> FluyerAppEngine {
    return try FfiConverterTypeFluyerAppEngine.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFluyerAppEngine_lower(_ value: FluyerAppEngine) -> UnsafeMutableRawPointer {
    return FfiConverterTypeFluyerAppEngine.lower(value)
}


public struct AlbumCardViewModel {
    public var index: UInt64
    public var name: String
    public var artist: String
    public var year: String
    public var trackCount: UInt64
    public var trackCountLabel: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(index: UInt64, name: String, artist: String, year: String, trackCount: UInt64, trackCountLabel: String) {
        self.index = index
        self.name = name
        self.artist = artist
        self.year = year
        self.trackCount = trackCount
        self.trackCountLabel = trackCountLabel
    }
}



extension AlbumCardViewModel: Equatable, Hashable {
    public static func ==(lhs: AlbumCardViewModel, rhs: AlbumCardViewModel) -> Bool {
        if lhs.index != rhs.index {
            return false
        }
        if lhs.name != rhs.name {
            return false
        }
        if lhs.artist != rhs.artist {
            return false
        }
        if lhs.year != rhs.year {
            return false
        }
        if lhs.trackCount != rhs.trackCount {
            return false
        }
        if lhs.trackCountLabel != rhs.trackCountLabel {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(index)
        hasher.combine(name)
        hasher.combine(artist)
        hasher.combine(year)
        hasher.combine(trackCount)
        hasher.combine(trackCountLabel)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAlbumCardViewModel: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AlbumCardViewModel {
        return
            try AlbumCardViewModel(
                index: FfiConverterUInt64.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                artist: FfiConverterString.read(from: &buf), 
                year: FfiConverterString.read(from: &buf), 
                trackCount: FfiConverterUInt64.read(from: &buf), 
                trackCountLabel: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: AlbumCardViewModel, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.index, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.artist, into: &buf)
        FfiConverterString.write(value.year, into: &buf)
        FfiConverterUInt64.write(value.trackCount, into: &buf)
        FfiConverterString.write(value.trackCountLabel, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAlbumCardViewModel_lift(_ buf: RustBuffer) throws -> AlbumCardViewModel {
    return try FfiConverterTypeAlbumCardViewModel.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAlbumCardViewModel_lower(_ value: AlbumCardViewModel) -> RustBuffer {
    return FfiConverterTypeAlbumCardViewModel.lower(value)
}


public struct AlbumDetailViewModel {
    public var header: AlbumCardViewModel
    public var durationMs: UInt64
    public var totalDurationFormatted: String
    public var subtitle: String
    public var tracks: [TrackItemViewModel]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(header: AlbumCardViewModel, durationMs: UInt64, totalDurationFormatted: String, subtitle: String, tracks: [TrackItemViewModel]) {
        self.header = header
        self.durationMs = durationMs
        self.totalDurationFormatted = totalDurationFormatted
        self.subtitle = subtitle
        self.tracks = tracks
    }
}



extension AlbumDetailViewModel: Equatable, Hashable {
    public static func ==(lhs: AlbumDetailViewModel, rhs: AlbumDetailViewModel) -> Bool {
        if lhs.header != rhs.header {
            return false
        }
        if lhs.durationMs != rhs.durationMs {
            return false
        }
        if lhs.totalDurationFormatted != rhs.totalDurationFormatted {
            return false
        }
        if lhs.subtitle != rhs.subtitle {
            return false
        }
        if lhs.tracks != rhs.tracks {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(header)
        hasher.combine(durationMs)
        hasher.combine(totalDurationFormatted)
        hasher.combine(subtitle)
        hasher.combine(tracks)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAlbumDetailViewModel: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AlbumDetailViewModel {
        return
            try AlbumDetailViewModel(
                header: FfiConverterTypeAlbumCardViewModel.read(from: &buf), 
                durationMs: FfiConverterUInt64.read(from: &buf), 
                totalDurationFormatted: FfiConverterString.read(from: &buf), 
                subtitle: FfiConverterString.read(from: &buf), 
                tracks: FfiConverterSequenceTypeTrackItemViewModel.read(from: &buf)
        )
    }

    public static func write(_ value: AlbumDetailViewModel, into buf: inout [UInt8]) {
        FfiConverterTypeAlbumCardViewModel.write(value.header, into: &buf)
        FfiConverterUInt64.write(value.durationMs, into: &buf)
        FfiConverterString.write(value.totalDurationFormatted, into: &buf)
        FfiConverterString.write(value.subtitle, into: &buf)
        FfiConverterSequenceTypeTrackItemViewModel.write(value.tracks, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAlbumDetailViewModel_lift(_ buf: RustBuffer) throws -> AlbumDetailViewModel {
    return try FfiConverterTypeAlbumDetailViewModel.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAlbumDetailViewModel_lower(_ value: AlbumDetailViewModel) -> RustBuffer {
    return FfiConverterTypeAlbumDetailViewModel.lower(value)
}


public struct ColorRgb {
    public var r: UInt8
    public var g: UInt8
    public var b: UInt8

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(r: UInt8, g: UInt8, b: UInt8) {
        self.r = r
        self.g = g
        self.b = b
    }
}



extension ColorRgb: Equatable, Hashable {
    public static func ==(lhs: ColorRgb, rhs: ColorRgb) -> Bool {
        if lhs.r != rhs.r {
            return false
        }
        if lhs.g != rhs.g {
            return false
        }
        if lhs.b != rhs.b {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(r)
        hasher.combine(g)
        hasher.combine(b)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeColorRgb: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ColorRgb {
        return
            try ColorRgb(
                r: FfiConverterUInt8.read(from: &buf), 
                g: FfiConverterUInt8.read(from: &buf), 
                b: FfiConverterUInt8.read(from: &buf)
        )
    }

    public static func write(_ value: ColorRgb, into buf: inout [UInt8]) {
        FfiConverterUInt8.write(value.r, into: &buf)
        FfiConverterUInt8.write(value.g, into: &buf)
        FfiConverterUInt8.write(value.b, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeColorRgb_lift(_ buf: RustBuffer) throws -> ColorRgb {
    return try FfiConverterTypeColorRgb.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeColorRgb_lower(_ value: ColorRgb) -> RustBuffer {
    return FfiConverterTypeColorRgb.lower(value)
}


public struct LyricLine {
    public var timestampMs: UInt64
    public var text: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(timestampMs: UInt64, text: String) {
        self.timestampMs = timestampMs
        self.text = text
    }
}



extension LyricLine: Equatable, Hashable {
    public static func ==(lhs: LyricLine, rhs: LyricLine) -> Bool {
        if lhs.timestampMs != rhs.timestampMs {
            return false
        }
        if lhs.text != rhs.text {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(timestampMs)
        hasher.combine(text)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLyricLine: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LyricLine {
        return
            try LyricLine(
                timestampMs: FfiConverterUInt64.read(from: &buf), 
                text: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: LyricLine, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.timestampMs, into: &buf)
        FfiConverterString.write(value.text, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLyricLine_lift(_ buf: RustBuffer) throws -> LyricLine {
    return try FfiConverterTypeLyricLine.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLyricLine_lower(_ value: LyricLine) -> RustBuffer {
    return FfiConverterTypeLyricLine.lower(value)
}


public struct PlayViewModel {
    public var track: TrackItemViewModel?
    public var lyrics: [LyricLine]
    public var currentLyricIndex: Int32
    public var palette: [ColorRgb]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(track: TrackItemViewModel?, lyrics: [LyricLine], currentLyricIndex: Int32, palette: [ColorRgb]) {
        self.track = track
        self.lyrics = lyrics
        self.currentLyricIndex = currentLyricIndex
        self.palette = palette
    }
}



extension PlayViewModel: Equatable, Hashable {
    public static func ==(lhs: PlayViewModel, rhs: PlayViewModel) -> Bool {
        if lhs.track != rhs.track {
            return false
        }
        if lhs.lyrics != rhs.lyrics {
            return false
        }
        if lhs.currentLyricIndex != rhs.currentLyricIndex {
            return false
        }
        if lhs.palette != rhs.palette {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(track)
        hasher.combine(lyrics)
        hasher.combine(currentLyricIndex)
        hasher.combine(palette)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePlayViewModel: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PlayViewModel {
        return
            try PlayViewModel(
                track: FfiConverterOptionTypeTrackItemViewModel.read(from: &buf), 
                lyrics: FfiConverterSequenceTypeLyricLine.read(from: &buf), 
                currentLyricIndex: FfiConverterInt32.read(from: &buf), 
                palette: FfiConverterSequenceTypeColorRgb.read(from: &buf)
        )
    }

    public static func write(_ value: PlayViewModel, into buf: inout [UInt8]) {
        FfiConverterOptionTypeTrackItemViewModel.write(value.track, into: &buf)
        FfiConverterSequenceTypeLyricLine.write(value.lyrics, into: &buf)
        FfiConverterInt32.write(value.currentLyricIndex, into: &buf)
        FfiConverterSequenceTypeColorRgb.write(value.palette, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePlayViewModel_lift(_ buf: RustBuffer) throws -> PlayViewModel {
    return try FfiConverterTypePlayViewModel.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePlayViewModel_lower(_ value: PlayViewModel) -> RustBuffer {
    return FfiConverterTypePlayViewModel.lower(value)
}


public struct PlayerBarViewModel {
    public var trackIndex: Int64
    public var title: String
    public var artist: String
    public var album: String
    public var positionMs: UInt64
    public var durationMs: UInt64
    public var progressPct: Float
    public var timeLabel: String
    public var isPlaying: Bool
    public var repeatMode: NativeRepeatMode
    public var isShuffled: Bool
    public var volume: Float

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(trackIndex: Int64, title: String, artist: String, album: String, positionMs: UInt64, durationMs: UInt64, progressPct: Float, timeLabel: String, isPlaying: Bool, repeatMode: NativeRepeatMode, isShuffled: Bool, volume: Float) {
        self.trackIndex = trackIndex
        self.title = title
        self.artist = artist
        self.album = album
        self.positionMs = positionMs
        self.durationMs = durationMs
        self.progressPct = progressPct
        self.timeLabel = timeLabel
        self.isPlaying = isPlaying
        self.repeatMode = repeatMode
        self.isShuffled = isShuffled
        self.volume = volume
    }
}



extension PlayerBarViewModel: Equatable, Hashable {
    public static func ==(lhs: PlayerBarViewModel, rhs: PlayerBarViewModel) -> Bool {
        if lhs.trackIndex != rhs.trackIndex {
            return false
        }
        if lhs.title != rhs.title {
            return false
        }
        if lhs.artist != rhs.artist {
            return false
        }
        if lhs.album != rhs.album {
            return false
        }
        if lhs.positionMs != rhs.positionMs {
            return false
        }
        if lhs.durationMs != rhs.durationMs {
            return false
        }
        if lhs.progressPct != rhs.progressPct {
            return false
        }
        if lhs.timeLabel != rhs.timeLabel {
            return false
        }
        if lhs.isPlaying != rhs.isPlaying {
            return false
        }
        if lhs.repeatMode != rhs.repeatMode {
            return false
        }
        if lhs.isShuffled != rhs.isShuffled {
            return false
        }
        if lhs.volume != rhs.volume {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(trackIndex)
        hasher.combine(title)
        hasher.combine(artist)
        hasher.combine(album)
        hasher.combine(positionMs)
        hasher.combine(durationMs)
        hasher.combine(progressPct)
        hasher.combine(timeLabel)
        hasher.combine(isPlaying)
        hasher.combine(repeatMode)
        hasher.combine(isShuffled)
        hasher.combine(volume)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePlayerBarViewModel: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PlayerBarViewModel {
        return
            try PlayerBarViewModel(
                trackIndex: FfiConverterInt64.read(from: &buf), 
                title: FfiConverterString.read(from: &buf), 
                artist: FfiConverterString.read(from: &buf), 
                album: FfiConverterString.read(from: &buf), 
                positionMs: FfiConverterUInt64.read(from: &buf), 
                durationMs: FfiConverterUInt64.read(from: &buf), 
                progressPct: FfiConverterFloat.read(from: &buf), 
                timeLabel: FfiConverterString.read(from: &buf), 
                isPlaying: FfiConverterBool.read(from: &buf), 
                repeatMode: FfiConverterTypeNativeRepeatMode.read(from: &buf), 
                isShuffled: FfiConverterBool.read(from: &buf), 
                volume: FfiConverterFloat.read(from: &buf)
        )
    }

    public static func write(_ value: PlayerBarViewModel, into buf: inout [UInt8]) {
        FfiConverterInt64.write(value.trackIndex, into: &buf)
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterString.write(value.artist, into: &buf)
        FfiConverterString.write(value.album, into: &buf)
        FfiConverterUInt64.write(value.positionMs, into: &buf)
        FfiConverterUInt64.write(value.durationMs, into: &buf)
        FfiConverterFloat.write(value.progressPct, into: &buf)
        FfiConverterString.write(value.timeLabel, into: &buf)
        FfiConverterBool.write(value.isPlaying, into: &buf)
        FfiConverterTypeNativeRepeatMode.write(value.repeatMode, into: &buf)
        FfiConverterBool.write(value.isShuffled, into: &buf)
        FfiConverterFloat.write(value.volume, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePlayerBarViewModel_lift(_ buf: RustBuffer) throws -> PlayerBarViewModel {
    return try FfiConverterTypePlayerBarViewModel.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePlayerBarViewModel_lower(_ value: PlayerBarViewModel) -> RustBuffer {
    return FfiConverterTypePlayerBarViewModel.lower(value)
}


public struct ScanStatusViewModel {
    public var isScanning: Bool
    public var current: UInt64
    public var total: UInt64
    public var progressPct: Float
    public var statusLabel: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(isScanning: Bool, current: UInt64, total: UInt64, progressPct: Float, statusLabel: String) {
        self.isScanning = isScanning
        self.current = current
        self.total = total
        self.progressPct = progressPct
        self.statusLabel = statusLabel
    }
}



extension ScanStatusViewModel: Equatable, Hashable {
    public static func ==(lhs: ScanStatusViewModel, rhs: ScanStatusViewModel) -> Bool {
        if lhs.isScanning != rhs.isScanning {
            return false
        }
        if lhs.current != rhs.current {
            return false
        }
        if lhs.total != rhs.total {
            return false
        }
        if lhs.progressPct != rhs.progressPct {
            return false
        }
        if lhs.statusLabel != rhs.statusLabel {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(isScanning)
        hasher.combine(current)
        hasher.combine(total)
        hasher.combine(progressPct)
        hasher.combine(statusLabel)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeScanStatusViewModel: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ScanStatusViewModel {
        return
            try ScanStatusViewModel(
                isScanning: FfiConverterBool.read(from: &buf), 
                current: FfiConverterUInt64.read(from: &buf), 
                total: FfiConverterUInt64.read(from: &buf), 
                progressPct: FfiConverterFloat.read(from: &buf), 
                statusLabel: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: ScanStatusViewModel, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.isScanning, into: &buf)
        FfiConverterUInt64.write(value.current, into: &buf)
        FfiConverterUInt64.write(value.total, into: &buf)
        FfiConverterFloat.write(value.progressPct, into: &buf)
        FfiConverterString.write(value.statusLabel, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeScanStatusViewModel_lift(_ buf: RustBuffer) throws -> ScanStatusViewModel {
    return try FfiConverterTypeScanStatusViewModel.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeScanStatusViewModel_lower(_ value: ScanStatusViewModel) -> RustBuffer {
    return FfiConverterTypeScanStatusViewModel.lower(value)
}


public struct TrackItemViewModel {
    public var index: UInt64
    public var path: String
    public var title: String
    public var artist: String
    public var album: String
    public var durationMs: UInt64
    public var durationFormatted: String
    public var isCurrent: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(index: UInt64, path: String, title: String, artist: String, album: String, durationMs: UInt64, durationFormatted: String, isCurrent: Bool) {
        self.index = index
        self.path = path
        self.title = title
        self.artist = artist
        self.album = album
        self.durationMs = durationMs
        self.durationFormatted = durationFormatted
        self.isCurrent = isCurrent
    }
}



extension TrackItemViewModel: Equatable, Hashable {
    public static func ==(lhs: TrackItemViewModel, rhs: TrackItemViewModel) -> Bool {
        if lhs.index != rhs.index {
            return false
        }
        if lhs.path != rhs.path {
            return false
        }
        if lhs.title != rhs.title {
            return false
        }
        if lhs.artist != rhs.artist {
            return false
        }
        if lhs.album != rhs.album {
            return false
        }
        if lhs.durationMs != rhs.durationMs {
            return false
        }
        if lhs.durationFormatted != rhs.durationFormatted {
            return false
        }
        if lhs.isCurrent != rhs.isCurrent {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(index)
        hasher.combine(path)
        hasher.combine(title)
        hasher.combine(artist)
        hasher.combine(album)
        hasher.combine(durationMs)
        hasher.combine(durationFormatted)
        hasher.combine(isCurrent)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTrackItemViewModel: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TrackItemViewModel {
        return
            try TrackItemViewModel(
                index: FfiConverterUInt64.read(from: &buf), 
                path: FfiConverterString.read(from: &buf), 
                title: FfiConverterString.read(from: &buf), 
                artist: FfiConverterString.read(from: &buf), 
                album: FfiConverterString.read(from: &buf), 
                durationMs: FfiConverterUInt64.read(from: &buf), 
                durationFormatted: FfiConverterString.read(from: &buf), 
                isCurrent: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: TrackItemViewModel, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.index, into: &buf)
        FfiConverterString.write(value.path, into: &buf)
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterString.write(value.artist, into: &buf)
        FfiConverterString.write(value.album, into: &buf)
        FfiConverterUInt64.write(value.durationMs, into: &buf)
        FfiConverterString.write(value.durationFormatted, into: &buf)
        FfiConverterBool.write(value.isCurrent, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTrackItemViewModel_lift(_ buf: RustBuffer) throws -> TrackItemViewModel {
    return try FfiConverterTypeTrackItemViewModel.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTrackItemViewModel_lower(_ value: TrackItemViewModel) -> RustBuffer {
    return FfiConverterTypeTrackItemViewModel.lower(value)
}


public enum FluyerError {

    
    
    case InitFailed(message: String
    )
    case OperationFailed(message: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFluyerError: FfiConverterRustBuffer {
    typealias SwiftType = FluyerError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FluyerError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InitFailed(
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .OperationFailed(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FluyerError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .InitFailed(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .OperationFailed(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


extension FluyerError: Equatable, Hashable {}

extension FluyerError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum FluyerEvent {
    
    case playerBarUpdated(vm: PlayerBarViewModel
    )
    case playViewUpdated(vm: PlayViewModel
    )
    case trackChanged(track: TrackItemViewModel?, index: UInt64
    )
    case libraryUpdated
    case scanProgress(vm: ScanStatusViewModel
    )
    case toast(message: String
    )
    case trackCoverLoaded(index: UInt64
    )
    case albumCoverLoaded(index: UInt64
    )
    case lyricsLoaded(lyrics: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFluyerEvent: FfiConverterRustBuffer {
    typealias SwiftType = FluyerEvent

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FluyerEvent {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .playerBarUpdated(vm: try FfiConverterTypePlayerBarViewModel.read(from: &buf)
        )
        
        case 2: return .playViewUpdated(vm: try FfiConverterTypePlayViewModel.read(from: &buf)
        )
        
        case 3: return .trackChanged(track: try FfiConverterOptionTypeTrackItemViewModel.read(from: &buf), index: try FfiConverterUInt64.read(from: &buf)
        )
        
        case 4: return .libraryUpdated
        
        case 5: return .scanProgress(vm: try FfiConverterTypeScanStatusViewModel.read(from: &buf)
        )
        
        case 6: return .toast(message: try FfiConverterString.read(from: &buf)
        )
        
        case 7: return .trackCoverLoaded(index: try FfiConverterUInt64.read(from: &buf)
        )
        
        case 8: return .albumCoverLoaded(index: try FfiConverterUInt64.read(from: &buf)
        )
        
        case 9: return .lyricsLoaded(lyrics: try FfiConverterString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FluyerEvent, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .playerBarUpdated(vm):
            writeInt(&buf, Int32(1))
            FfiConverterTypePlayerBarViewModel.write(vm, into: &buf)
            
        
        case let .playViewUpdated(vm):
            writeInt(&buf, Int32(2))
            FfiConverterTypePlayViewModel.write(vm, into: &buf)
            
        
        case let .trackChanged(track,index):
            writeInt(&buf, Int32(3))
            FfiConverterOptionTypeTrackItemViewModel.write(track, into: &buf)
            FfiConverterUInt64.write(index, into: &buf)
            
        
        case .libraryUpdated:
            writeInt(&buf, Int32(4))
        
        
        case let .scanProgress(vm):
            writeInt(&buf, Int32(5))
            FfiConverterTypeScanStatusViewModel.write(vm, into: &buf)
            
        
        case let .toast(message):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .trackCoverLoaded(index):
            writeInt(&buf, Int32(7))
            FfiConverterUInt64.write(index, into: &buf)
            
        
        case let .albumCoverLoaded(index):
            writeInt(&buf, Int32(8))
            FfiConverterUInt64.write(index, into: &buf)
            
        
        case let .lyricsLoaded(lyrics):
            writeInt(&buf, Int32(9))
            FfiConverterString.write(lyrics, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFluyerEvent_lift(_ buf: RustBuffer) throws -> FluyerEvent {
    return try FfiConverterTypeFluyerEvent.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFluyerEvent_lower(_ value: FluyerEvent) -> RustBuffer {
    return FfiConverterTypeFluyerEvent.lower(value)
}



extension FluyerEvent: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum NativeRepeatMode : UInt8 {
    
    case none = 0
    case all = 1
    case one = 2
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNativeRepeatMode: FfiConverterRustBuffer {
    typealias SwiftType = NativeRepeatMode

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NativeRepeatMode {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .none
        
        case 2: return .all
        
        case 3: return .one
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: NativeRepeatMode, into buf: inout [UInt8]) {
        switch value {
        
        
        case .none:
            writeInt(&buf, Int32(1))
        
        
        case .all:
            writeInt(&buf, Int32(2))
        
        
        case .one:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativeRepeatMode_lift(_ buf: RustBuffer) throws -> NativeRepeatMode {
    return try FfiConverterTypeNativeRepeatMode.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativeRepeatMode_lower(_ value: NativeRepeatMode) -> RustBuffer {
    return FfiConverterTypeNativeRepeatMode.lower(value)
}



extension NativeRepeatMode: Equatable, Hashable {}






public protocol FluyerEventListener : AnyObject {
    
    func onEvent(event: FluyerEvent) 
    
}

// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceFluyerEventListener {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    static var vtable: UniffiVTableCallbackInterfaceFluyerEventListener = UniffiVTableCallbackInterfaceFluyerEventListener(
        onEvent: { (
            uniffiHandle: UInt64,
            event: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceFluyerEventListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onEvent(
                     event: try FfiConverterTypeFluyerEvent.lift(event)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterCallbackInterfaceFluyerEventListener.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface FluyerEventListener: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitFluyerEventListener() {
    uniffi_fluyer_core_fn_init_callback_vtable_fluyereventlistener(&UniffiCallbackInterfaceFluyerEventListener.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceFluyerEventListener {
    fileprivate static var handleMap = UniffiHandleMap<FluyerEventListener>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceFluyerEventListener : FfiConverter {
    typealias SwiftType = FluyerEventListener
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeAlbumCardViewModel: FfiConverterRustBuffer {
    typealias SwiftType = AlbumCardViewModel?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeAlbumCardViewModel.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeAlbumCardViewModel.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeAlbumDetailViewModel: FfiConverterRustBuffer {
    typealias SwiftType = AlbumDetailViewModel?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeAlbumDetailViewModel.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeAlbumDetailViewModel.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeTrackItemViewModel: FfiConverterRustBuffer {
    typealias SwiftType = TrackItemViewModel?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeTrackItemViewModel.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeTrackItemViewModel.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionCallbackInterfaceFluyerEventListener: FfiConverterRustBuffer {
    typealias SwiftType = FluyerEventListener?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterCallbackInterfaceFluyerEventListener.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterCallbackInterfaceFluyerEventListener.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeColorRgb: FfiConverterRustBuffer {
    typealias SwiftType = [ColorRgb]

    public static func write(_ value: [ColorRgb], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeColorRgb.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ColorRgb] {
        let len: Int32 = try readInt(&buf)
        var seq = [ColorRgb]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeColorRgb.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeLyricLine: FfiConverterRustBuffer {
    typealias SwiftType = [LyricLine]

    public static func write(_ value: [LyricLine], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeLyricLine.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [LyricLine] {
        let len: Int32 = try readInt(&buf)
        var seq = [LyricLine]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeLyricLine.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeTrackItemViewModel: FfiConverterRustBuffer {
    typealias SwiftType = [TrackItemViewModel]

    public static func write(_ value: [TrackItemViewModel], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeTrackItemViewModel.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [TrackItemViewModel] {
        let len: Int32 = try readInt(&buf)
        var seq = [TrackItemViewModel]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeTrackItemViewModel.read(from: &buf))
        }
        return seq
    }
}
public func formatTimeLabel(ms: UInt64) -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_fluyer_core_fn_func_format_time_label(
        FfiConverterUInt64.lower(ms),$0
    )
})
}
public func parseLrcLyrics(lrcText: String) -> [LyricLine] {
    return try!  FfiConverterSequenceTypeLyricLine.lift(try! rustCall() {
    uniffi_fluyer_core_fn_func_parse_lrc_lyrics(
        FfiConverterString.lower(lrcText),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_fluyer_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_fluyer_core_checksum_func_format_time_label() != 52881) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fluyer_core_checksum_func_parse_lrc_lyrics() != 60133) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fluyer_core_checksum_method_fluyerappengine_cycle_repeat() != 39027) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fluyer_core_checksum_method_fluyerappengine_generate_background_for_current() != 47697) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fluyer_core_checksum_method_fluyerappengine_get_active_lyric_index() != 35442) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fluyer_core_checksum_method_fluyerappengine_get_album_card() != 10560) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fluyer_core_checksum_method_fluyerappengine_get_album_count() != 36969) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fluyer_core_checksum_method_fluyerappengine_get_album_detail() != 49270) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fluyer_core_checksum_method_fluyerappengine_get_album_image() != 8223) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fluyer_core_checksum_method_fluyerappengine_get_album_thumbnail_rgba() != 35604) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fluyer_core_checksum_method_fluyerappengine_get_album_tracks() != 23190) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fluyer_core_checksum_method_fluyerappengine_get_album_view() != 60993) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fluyer_core_checksum_method_fluyerappengine_get_current_image() != 14012) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fluyer_core_checksum_method_fluyerappengine_get_lyrics() != 3464) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fluyer_core_checksum_method_fluyerappengine_get_play_view() != 52488) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fluyer_core_checksum_method_fluyerappengine_get_player_bar_view() != 64426) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fluyer_core_checksum_method_fluyerappengine_get_scan_status() != 20235) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fluyer_core_checksum_method_fluyerappengine_get_track_count() != 42709) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fluyer_core_checksum_method_fluyerappengine_get_track_image() != 12325) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fluyer_core_checksum_method_fluyerappengine_get_track_thumbnail_rgba() != 54932) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fluyer_core_checksum_method_fluyerappengine_get_track_view() != 48451) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fluyer_core_checksum_method_fluyerappengine_next() != 33101) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fluyer_core_checksum_method_fluyerappengine_pause() != 65069) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fluyer_core_checksum_method_fluyerappengine_play() != 64620) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fluyer_core_checksum_method_fluyerappengine_play_album() != 19961) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fluyer_core_checksum_method_fluyerappengine_play_album_track() != 10505) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fluyer_core_checksum_method_fluyerappengine_play_all_from_library() != 64362) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fluyer_core_checksum_method_fluyerappengine_play_single_from_library() != 55280) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fluyer_core_checksum_method_fluyerappengine_previous() != 6186) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fluyer_core_checksum_method_fluyerappengine_queue_album() != 55067) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fluyer_core_checksum_method_fluyerappengine_request_sync() != 59451) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fluyer_core_checksum_method_fluyerappengine_scan_directories() != 24830) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fluyer_core_checksum_method_fluyerappengine_seek() != 54539) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fluyer_core_checksum_method_fluyerappengine_set_repeat_mode() != 52718) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fluyer_core_checksum_method_fluyerappengine_set_volume() != 38895) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fluyer_core_checksum_method_fluyerappengine_shuffle() != 7595) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fluyer_core_checksum_method_fluyerappengine_shuffle_album() != 38700) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fluyer_core_checksum_method_fluyerappengine_toggle_play() != 3078) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fluyer_core_checksum_constructor_fluyerappengine_new() != 38275) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_fluyer_core_checksum_method_fluyereventlistener_on_event() != 65370) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitFluyerEventListener()
    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all