name: Build & Publish

on:
  workflow_dispatch:
    inputs:
      release_build:
        description: 'Publish as Release'
        type: boolean
        default: false
      build_windows_x86_64:
        description: 'Build windows-x86_64'
        type: boolean
        default: true
      build_macos_intel:
        description: 'Build macos-intel'
        type: boolean
        default: true
      build_macos_silicon:
        description: 'Build macos-silicon'
        type: boolean
        default: true
      build_linux:
        description: 'Build linux'
        type: boolean
        default: true
      build_android_armv7:
        description: 'Build android-armv7'
        type: boolean
        default: true
      build_android_aarch64:
        description: 'Build android-aarch64'
        type: boolean
        default: true
      build_android_i686:
        description: 'Build android-i686'
        type: boolean
        default: true
      build_android_x86_64:
        description: 'Build android-x86_64'
        type: boolean
        default: true

env:
  RUST_BACKTRACE: 1
  TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
  TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Get version
        id: version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  build-windows-x86_64:
    needs: prepare
    if: ${{ inputs.build_windows_x86_64 }}
    runs-on: windows-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
      - name: Setup Workflow
        shell: bash
        run: bash infra/windows.sh
      - name: Upload artifact
        if: ${{ !inputs.release_build }}
        uses: actions/upload-artifact@v4
        with:
          name: windows-x86_64
          path: ./src-tauri/target/release/bundle/nsis/Fluyer_*.exe
      - name: Publish release
        if: ${{ inputs.release_build }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            ./src-tauri/target/release/bundle/nsis/Fluyer_*.exe
            ./src-tauri/target/release/bundle/nsis/Fluyer_*.exe.sig
          tag: v${{ needs.prepare.outputs.version }}
          name: Fluyer v${{ needs.prepare.outputs.version }}
          allowUpdates: true
          omitBodyDuringUpdate: true
          prerelease: true
          artifactErrorsFailBuild: true
          token: ${{ secrets.GITHUB_TOKEN }}

  build-macos-intel:
    needs: prepare
    if: ${{ inputs.build_macos_intel }}
    runs-on: macos-15-intel
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
      - name: Setup Workflow
        shell: bash
        run: bash infra/macos.sh
      - name: Rename macOS App bundle
        run: |
          mv ./src-tauri/target/release/bundle/macos/Fluyer.app.tar.gz ./src-tauri/target/release/bundle/macos/Fluyer_${{ needs.prepare.outputs.version }}_x64.app.tar.gz
          mv ./src-tauri/target/release/bundle/macos/Fluyer.app.tar.gz.sig ./src-tauri/target/release/bundle/macos/Fluyer_${{ needs.prepare.outputs.version }}_x64.app.tar.gz.sig
      - name: Upload artifact
        if: ${{ !inputs.release_build }}
        uses: actions/upload-artifact@v4
        with:
          name: macos-intel
          path: ./src-tauri/target/release/bundle/dmg/Fluyer_*_x64.dmg
      - name: Publish release
        if: ${{ inputs.release_build }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            ./src-tauri/target/release/bundle/dmg/Fluyer_*_x64.dmg
            ./src-tauri/target/release/bundle/macos/Fluyer_*_x64.app.tar.gz
            ./src-tauri/target/release/bundle/macos/Fluyer_*_x64.app.tar.gz.sig
          tag: v${{ needs.prepare.outputs.version }}
          name: Fluyer v${{ needs.prepare.outputs.version }}
          allowUpdates: true
          omitBodyDuringUpdate: true
          prerelease: true
          artifactErrorsFailBuild: true
          token: ${{ secrets.GITHUB_TOKEN }}

  build-macos-silicon:
    needs: prepare
    if: ${{ inputs.build_macos_silicon }}
    runs-on: macos-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
      - name: Setup Workflow
        shell: bash
        run: bash infra/macos.sh
      - name: Rename macOS App bundle
        run: |
          mv ./src-tauri/target/release/bundle/macos/Fluyer.app.tar.gz ./src-tauri/target/release/bundle/macos/Fluyer_${{ needs.prepare.outputs.version }}_aarch64.app.tar.gz
          mv ./src-tauri/target/release/bundle/macos/Fluyer.app.tar.gz.sig ./src-tauri/target/release/bundle/macos/Fluyer_${{ needs.prepare.outputs.version }}_aarch64.app.tar.gz.sig
      - name: Upload artifact
        if: ${{ !inputs.release_build }}
        uses: actions/upload-artifact@v4
        with:
          name: macos-silicon
          path: ./src-tauri/target/release/bundle/dmg/Fluyer_*_aarch64.dmg
      - name: Publish release
        if: ${{ inputs.release_build }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            ./src-tauri/target/release/bundle/dmg/Fluyer_*_aarch64.dmg
            ./src-tauri/target/release/bundle/macos/Fluyer_*_aarch64.app.tar.gz
            ./src-tauri/target/release/bundle/macos/Fluyer_*_aarch64.app.tar.gz.sig
          tag: v${{ needs.prepare.outputs.version }}
          name: Fluyer v${{ needs.prepare.outputs.version }}
          allowUpdates: true
          omitBodyDuringUpdate: true
          prerelease: true
          artifactErrorsFailBuild: true
          token: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    needs: prepare
    if: ${{ inputs.build_linux }}
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
      - name: Setup Workflow
        shell: bash
        run: bash infra/linux.sh
      - name: Upload artifact
        if: ${{ !inputs.release_build }}
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: ./src-tauri/target/release/bundle/deb/Fluyer_*_amd64.deb
      - name: Publish release
        if: ${{ inputs.release_build }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            ./src-tauri/target/release/bundle/deb/Fluyer_*_amd64.deb
          tag: v${{ needs.prepare.outputs.version }}
          name: Fluyer v${{ needs.prepare.outputs.version }}
          allowUpdates: true
          omitBodyDuringUpdate: true
          prerelease: true
          artifactErrorsFailBuild: true
          token: ${{ secrets.GITHUB_TOKEN }}

  build-android-armv7:
    needs: prepare
    if: ${{ inputs.build_android_armv7 }}
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Install NDK
        run: sdkmanager "ndk;28.0.13004108"
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: armv7-linux-androideabi
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
      - name: Setup Workflow
        shell: bash
        env:
          ANDROID_ARCH: armv7
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_KEY_BASE64: ${{ secrets.ANDROID_KEY_BASE64 }}
          RUNNER_TEMP: ${{ runner.temp }}
          NDK_HOME: ${{ env.ANDROID_HOME }}/ndk/28.0.13004108
        run: bash infra/android.sh
      - name: Rename Android APK
        run: mv ./src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release.apk ./Fluyer_${{ needs.prepare.outputs.version }}_armv7.apk
      - name: Upload artifact
        if: ${{ !inputs.release_build }}
        uses: actions/upload-artifact@v4
        with:
          name: android-armv7
          path: ./Fluyer_*_armv7.apk
      - name: Publish release
        if: ${{ inputs.release_build }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./Fluyer_*_armv7.apk
          tag: v${{ needs.prepare.outputs.version }}
          name: Fluyer v${{ needs.prepare.outputs.version }}
          allowUpdates: true
          omitBodyDuringUpdate: true
          prerelease: true
          artifactErrorsFailBuild: true
          token: ${{ secrets.GITHUB_TOKEN }}

  build-android-aarch64:
    needs: prepare
    if: ${{ inputs.build_android_aarch64 }}
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Install NDK
        run: sdkmanager "ndk;28.0.13004108"
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
      - name: Setup Workflow
        shell: bash
        env:
          ANDROID_ARCH: aarch64
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_KEY_BASE64: ${{ secrets.ANDROID_KEY_BASE64 }}
          RUNNER_TEMP: ${{ runner.temp }}
          NDK_HOME: ${{ env.ANDROID_HOME }}/ndk/28.0.13004108
        run: bash infra/android.sh
      - name: Rename Android APK
        run: mv ./src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release.apk ./Fluyer_${{ needs.prepare.outputs.version }}_aarch64.apk
      - name: Upload artifact
        if: ${{ !inputs.release_build }}
        uses: actions/upload-artifact@v4
        with:
          name: android-aarch64
          path: ./Fluyer_*_aarch64.apk
      - name: Publish release
        if: ${{ inputs.release_build }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./Fluyer_*_aarch64.apk
          tag: v${{ needs.prepare.outputs.version }}
          name: Fluyer v${{ needs.prepare.outputs.version }}
          allowUpdates: true
          omitBodyDuringUpdate: true
          prerelease: true
          artifactErrorsFailBuild: true
          token: ${{ secrets.GITHUB_TOKEN }}

  build-android-i686:
    needs: prepare
    if: ${{ inputs.build_android_i686 }}
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Install NDK
        run: sdkmanager "ndk;28.0.13004108"
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: i686-linux-android
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
      - name: Setup Workflow
        shell: bash
        env:
          ANDROID_ARCH: i686
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_KEY_BASE64: ${{ secrets.ANDROID_KEY_BASE64 }}
          RUNNER_TEMP: ${{ runner.temp }}
          NDK_HOME: ${{ env.ANDROID_HOME }}/ndk/28.0.13004108
        run: bash infra/android.sh
      - name: Rename Android APK
        run: mv ./src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release.apk ./Fluyer_${{ needs.prepare.outputs.version }}_i686.apk
      - name: Upload artifact
        if: ${{ !inputs.release_build }}
        uses: actions/upload-artifact@v4
        with:
          name: android-i686
          path: ./Fluyer_*_i686.apk
      - name: Publish release
        if: ${{ inputs.release_build }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./Fluyer_*_i686.apk
          tag: v${{ needs.prepare.outputs.version }}
          name: Fluyer v${{ needs.prepare.outputs.version }}
          allowUpdates: true
          omitBodyDuringUpdate: true
          prerelease: true
          artifactErrorsFailBuild: true
          token: ${{ secrets.GITHUB_TOKEN }}

  build-android-x86_64:
    needs: prepare
    if: ${{ inputs.build_android_x86_64 }}
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Install NDK
        run: sdkmanager "ndk;28.0.13004108"
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-linux-android
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
      - name: Setup Workflow
        shell: bash
        env:
          ANDROID_ARCH: x86_64
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_KEY_BASE64: ${{ secrets.ANDROID_KEY_BASE64 }}
          RUNNER_TEMP: ${{ runner.temp }}
          NDK_HOME: ${{ env.ANDROID_HOME }}/ndk/28.0.13004108
        run: bash infra/android.sh
      - name: Rename Android APK
        run: mv ./src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release.apk ./Fluyer_${{ needs.prepare.outputs.version }}_x86_64.apk
      - name: Upload artifact
        if: ${{ !inputs.release_build }}
        uses: actions/upload-artifact@v4
        with:
          name: android-x86_64
          path: ./Fluyer_*_x86_64.apk
      - name: Publish release
        if: ${{ inputs.release_build }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./Fluyer_*_x86_64.apk
          tag: v${{ needs.prepare.outputs.version }}
          name: Fluyer v${{ needs.prepare.outputs.version }}
          allowUpdates: true
          omitBodyDuringUpdate: true
          prerelease: true
          artifactErrorsFailBuild: true
          token: ${{ secrets.GITHUB_TOKEN }}

  publish-updater:
    needs: prepare
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Generate latest.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APP_VERSION: ${{ needs.prepare.outputs.version }}
          GITHUB_REPO: ${{ github.repository }}
        run: |
          pnpm i
          pnpm tsx scripts/generate-updater-json.ts
      - name: Publish latest.json
        uses: ncipollo/release-action@v1
        with:
          artifacts: latest.json
          tag: v${{ needs.prepare.outputs.version }}
          name: Fluyer v${{ needs.prepare.outputs.version }}
          allowUpdates: true
          omitBodyDuringUpdate: true
          prerelease: true
          artifactErrorsFailBuild: true
          token: ${{ secrets.GITHUB_TOKEN }}
